"""add_wiki_workspace_tables

Revision ID: 9792604a8a1f
Revises: f87954945cc7
Create Date: 2026-05-17 17:38:30.188511

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9792604a8a1f'
down_revision: Union[str, None] = 'f87954945cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pages_user_id'), 'wiki_pages', ['user_id'], unique=False)
    op.create_table('workspace_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('open_pages', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_snapshots_user_id'), 'workspace_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_snapshots_user_id'), table_name='workspace_snapshots')
    op.drop_table('workspace_snapshots')
    op.drop_index(op.f('ix_wiki_pages_user_id'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    # ### end Alembic commands ###
